### PR TITLE
[Bugfix] GitHub submodule icons

### LINKED ISSUE #75: Symlink icons are not preserved
This has been fixed in #3, but is now a regression.

Example: https://github.com/lxqt/lxqt

Native:

image

With extension:

image

### LINKED ISSUE #92: Folder Icons Not Shown When Used as Submodules
Here is an example:

Capture d’écran 2024-07-04 à 11 14 01

It should have this icon:

Capture d’écran 2024-07-04 à 11 14 36

Thanks in advance !

### PR DESCRIPTION
**Pull request by mikeydevelops**
Fixes #92, where submodule name was not correctly detected when choosing an icon.

Added additional fix where when there are nested folders, the extension checks the top most level for the icon instead of the last level, now working like in vscode.

I think we can close #75, too.

### CODE REVIEW

File: src/lib/replace-icon.ts [hunk 1]
```diff
@@ -28,8 +28,13 @@ export function replaceIconInRow(
...
     .querySelector(provider.selectors.filename)
-    ?.textContent?.split('/')[0]
-    .trim();
+    ?.textContent// get the last folder for the icon
+    ?.split('/')
+    .reverse()[0]
+    .trim()
+    // remove possible sha from submodule
+    // matches 4 or more to future proof in case they decide to increase it.
+    .replace(/\s+@\s+[a-fA-F0-9]{4,}$/, '');
```
Comment (PKief) [inline src/lib/replace-icon.ts:37]: I'm wondering if the regular expression is needed here. As far as I understood the logic, we simply want to remove the hash code after the filename. So wouldn't is be possible to use a `split` function for this?

```suggestion
    .split('@')[0].trim()
```

The split divides the filename into two parts: the part before the "@" and the part after it. In this case we're using the first part by using `.split('@')[0]` and trim it afterwards. I don't expect that there's something after the hash code. 

What do you think about this? Am I missing something or can the complexity be reduced a bit by removing the regular expression?

Comment (mikeydevelops) [reply src/lib/replace-icon.ts:37]: @ symbol can exist for a folder name, and since the developer can decide what to call their submodule, it is possible for them to use the symbol as a name for the folder. This is just feature proofing. We know there are currently no icons matching the @ symbol, but who knows what the future holds.

Comment (PKief) [reply src/lib/replace-icon.ts:37]: I was just thinking, and maybe your approach is safer if the filename itself also includes an "@" symbol, right? 😅 Probably we should keep the regex.

Comment (mikeydevelops) [reply src/lib/replace-icon.ts:37]: I think we commented at the same time, if you want you can wait to see other people's opinions. I am for the regex.

Comment (PKief) [reply src/lib/replace-icon.ts:37]: Yes, it looks like :) I'm also for the regex approach now!

**Review by PKief — APPROVED** [review]
